config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
    controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :artworks do
    patch  "bookings/:id", to: "bookings#accept_booking", as: :confirm_booking
    put  "bookings/:id", to: "bookings#refuse_booking", as: :refuse_booking
    resources :bookings, only: [:create, :destroy]
  end

  get '/profile', to: 'profile#index'
  post '/subscribe', to: 'pages#subscribe'

  resources :bookings, only: [] do
    resources :reviews, only: :create
  end

  get 'mine', to: 'artworks#mine', as: :mine
  get '/contact' => 'pages#contact'
  get '/about' => 'pages#about'
  get '/dashboard', to: 'dashboard#index'

  scope module: 'users' do
    resources :users, only: [:show]
  end

end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
     @artworks = Artwork.where(user: current_user)
     @bookings = Booking.where(user: current_user)
     @bookings_on_my_artworks = bookings_on_user_artworks
  end

  private

  def bookings_on_user_artworks
    Booking.all.select {|booking| current_user.artworks.include? booking.artwork}
  end
end

app/helpers/dashboard_helper.rb
module DashboardHelper
  # def image_helper(artwork)
  #   if artwork.photo.present?
  #     "cl_image_path artwork.photo, width: 175, crop: :fill"
  #   else
  #     "fdmzro1il29ghsgunrwz"
  #   end
  # end
  # def artwork_photo_or_placeholder(artwork)
  #   if artwork.photo.present?
  #     artwork.photo
  #   else
  #     "fdmzro1il29ghsgunrwz"
  #   end
  # end
end

app/views/dashboard/_bookings_on_my_artworks.html.erb
<div class="tab-content hidden" id="bookings_on_my_artworks">
  <div class="list">
    <% if @bookings_on_my_artworks != [] %>
      <% pending_bookings = @bookings_on_my_artworks.select { |hash| hash[:status] == "Pending"} %>
      <% confirmed_bookings = @bookings_on_my_artworks.select { |hash| hash[:status] == "Confirmed"} %>
      <% refused_bookings = @bookings_on_my_artworks.select { |hash| hash[:status] == "Refused"} %>
      <% pending_bookings.sort { |hash| hash[:starts_on] }.each do |booking_on_my_artworks| %>
        <%= render 'create_cards_boma', booking_on_my_artworks: booking_on_my_artworks %>
      <% end %>
      <% confirmed_bookings.sort { |hash| hash[:starts_on] }.each do |booking_on_my_artworks| %>
        <%= render 'create_cards_boma', booking_on_my_artworks: booking_on_my_artworks %>
      <% end %>
      <% refused_bookings.sort { |hash| hash[:starts_on] }.each do |booking_on_my_artworks| %>
        <%= render 'create_cards_boma', booking_on_my_artworks: booking_on_my_artworks %>
      <% end %>
    <% else %>
      <div class="product">
        <div class='product-div'>
          <h3> No bookings on my artworks yet.</h3>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/dashboard/_create_cards_boma.html.erb
<div class="product <%= booking_on_my_artworks.status == "Refused" ? "product-declined" : "" %>">
  <div class="photo-div">
  <%= link_to artwork_path(booking_on_my_artworks.artwork) do %>
    <%= cl_image_tag(booking_on_my_artworks.artwork.photo, width: 400, height: 600, crop: :limit, class:"product-image") %>
    <% end %>
  </div>
  <div class='product-body'>
    <h3> <%= booking_on_my_artworks.artwork.name %> </h3>
    <p> <strong>Starts on:</strong> <%= booking_on_my_artworks.starts_on.strftime('%a %d %b %Y') %> </p>
    <p> <strong>Ends on:</strong> <%= booking_on_my_artworks.ends_on.strftime('%a %d %b %Y') %> </p>
    <p> <strong>Booked by:</strong> <%= link_to booking_on_my_artworks.user.email, user_path(booking_on_my_artworks.user) %></p>
    <p> <strong>Price:</strong> <%= booking_on_my_artworks.price %> €</p>
  </div>


  <div id="status-ajax">

    <div class='product-status'>
      <% if booking_on_my_artworks.status == "Confirmed" %>
      <span class="accept-green"><i class="fa fa-check" aria-hidden="true"></i> confirmed</span>
      <% elsif booking_on_my_artworks.status == "Refused"  %>
      <span class="refuse-red"><i class="fa fa-times" aria-hidden="true"></i> declined</span>
      <% end %>
    </div>

    <% if booking_on_my_artworks.status == "Pending" %>
    <ul class="list-inline product-controls">
      <li>        
        <%= link_to artwork_confirm_booking_path(booking_on_my_artworks.artwork, booking_on_my_artworks), method: :patch, class: "accept-green" do %>
        <span><i class="fa fa-check" aria-hidden="true"></i> confirm</span>
        <% end %>
      </li>
      <li>        
        <%= link_to artwork_refuse_booking_path(booking_on_my_artworks.artwork, booking_on_my_artworks), method: :put, class: "refuse-red" do %>
        <i class="fa fa-ban" aria-hidden="true"></i> refuse
        <% end %>
      </li>
    </ul>

    <% else %>

    <ul class="list-inline product-controls <%= booking_on_my_artworks.status == "Refused" ? "" : "product-controls-hidden" %>">
      <li>
        <% if booking_on_my_artworks.status == "Refused"  %>
        <%= link_to artwork_booking_path(booking_on_my_artworks.artwork, booking_on_my_artworks), class: "control-hover", method: :delete do %>
        <i class="fa fa-trash" aria-hidden="true"></i> remove
        <% end %>
        <% else %>
        <%= link_to artwork_booking_path(booking_on_my_artworks.artwork, booking_on_my_artworks), class: "control-hover", method: :delete do %>
        <i class="fa fa-ban" aria-hidden="true"></i> cancel
        <% end %>
        <% end %>
      </li>
    </ul>

    <% end %>
  </div>
</div>

app/views/dashboard/_my_artworks.html.erb
<div class="tab-content hidden" id="artworks">
  <div class="list">
    <div class="button-div">
      <%= link_to "List a new artwork", new_artwork_path, class: "btn btn-rounded" %>
    </div>
    <% if @artworks != [] %>
    <% @artworks.each do |artwork| %>

    <div class="product">
      <div class="photo-div">
      <%= link_to artwork_path(artwork) do %>
        <%= cl_image_tag(artwork.photo, width: 400, height: 600, crop: :limit, class:"product-image") %>
        <% end %>
      </div>
      <div class='product-body'>
        <h3> <%= artwork.name %> </h3>
        <p> <%= artwork.artist_name %></p>
        <p> <%= artwork.price %> € per day</p>
      </div>
      <ul class="list-inline product-controls product-controls-hidden hidden-sm hidden-xs">
        <li>
          <%= link_to edit_artwork_path(artwork), class: "control-hover" do %>
          <i class="fa fa-pencil-square-o" aria-hidden="true"></i> edit
          <% end %>
        </li>
        <li>

          <%= link_to artwork_path(artwork), class: "control-hover", method: :delete do %>
          <i class="fa fa-trash" aria-hidden="true"></i> delete
          <% end %>
        </li>
      </ul>
    </div>
    <% end -%>
    <% else %>
    <div class="product">
      <div class='product-body'>
        <h3> No artworks listed yet.</h3>
      </div>
    </div>
    <% end %>
  </div>
</div>

app/views/dashboard/_my_bookings.html.erb
<div class="tab-content" id="bookings">
  <div class="list">
    <% if @bookings != [] %>
    <% @bookings.sort { |a, b| [a[:status], a[:starts_on]] <=> [b[:status], b[:starts_on]] }.each do |booking| %>

    <div class="product <%= booking.status == "Refused" ? "product-declined" : "" %> ">
      <div class="photo-div">
      <%= link_to artwork_path(booking.artwork) do %>
        <%= cl_image_tag(booking.artwork.photo, width: 400, height: 600, crop: :limit, class:"product-image") %>
        <% end %>
      </div>
      
      <div class='product-body'>
        <h3> <%= booking.artwork.name %> </h3>
        <p> <strong>Starts on:</strong> <%= booking.starts_on.strftime('%a %d %b %Y') %> </p>
        <p> <strong>Ends on:</strong> <%= booking.ends_on.strftime('%a %d %b %Y') %> </p>
        <p> <strong>Owner:</strong> <%= link_to booking.artwork.user.email, user_path(booking.artwork.user) %></p>
        <p> <strong>Price:</strong> <%= booking.price %> €</p>
      </div>

      <div class='product-status'>
        <% if booking.status == "Pending" %>
          <span class="pending-yellow"><i class="fa fa-hourglass-half" aria-hidden="true"></i> pending</span>
        <% elsif booking.status == "Confirmed" %>
          <span class="accept-green"><i class="fa fa-check" aria-hidden="true"></i> confirmed</span>
        <% else %>
          <span class="refuse-red"><i class="fa fa-times" aria-hidden="true"></i> declined</span>
        <% end %>
      </div>
      
      <ul class="list-inline product-controls <%= booking.status == "Refused" ? "" : "product-controls-hidden" %>">
        <li>
          <% if booking.status == "Refused"  %>
            <%= link_to artwork_booking_path(booking.artwork, booking), class: "control-hover", method: :delete do %>
              <i class="fa fa-trash" aria-hidden="true"></i> delete
            <% end %>
          <% else %>
            <%= link_to artwork_booking_path(booking.artwork, booking), class: "control-hover", method: :delete do %>
              <i class="fa fa-ban" aria-hidden="true"></i> cancel
            <% end %>
          <% end %>
        </li>
      </ul>
    </div>
    <% end -%>
    <% else %>
    <div class="product">
      <div class='product-body'>
        <h3> No bookings yet.</h3>
      </div>
    </div>
    <% end %>
  </div>
</div>

app/views/dashboard/index.html.erb
  <div class="container text-center ">
   <h1 class="dashboard-title">My <span class="minted">art</span>board</h1>
   <div class="row">
     <div class="col-xs-8 col-xs-offset-2">
       <div class="">
        <div id="profiler">
          <% avatar_url = current_user.facebook_picture_url || default_avatar = "https://galerie.alittlemarket.com/galerie/sell/2626440/peintures-tableau-acrylique-abstrait-moderne-19314354-20161029-14541891a7-f00a9_big.jpg" %>
          <%= image_tag avatar_url, class: "avatar-large"%>
          <div>
            <% if current_user.first_name != nil  %>
            <h4> <%= current_user.first_name %></h4>
            <h4> <%= current_user.last_name %></h4>
            <% else %>
            <h5> <%= current_user.email %></h5>
            <% end %>
          </div>
        </div>
        <%= link_to " Edit your profile", edit_user_registration_path, class: "btn btn-booking-dash" %>
      </div>
    </div>
  </div>
</div>

<div class="container text-center">
  <div class="tabs">
    <a class="tab active" data-target="#bookings" id="my-bookings-tab">
      <h3>MY BOOKINGS</h3>
    </a>
    <a class="tab" data-target="#artworks" id="my-artworks-tab">
      <h3>MY ARTWORKS</h3>
    </a>
    <a class="tab" data-target="#bookings_on_my_artworks" id="bookings-tab">
      <h3>BOOKINGS ON MY ARTWORKS</h3>
    </a>
  </div>
</div>

<div class="container">

  <%= render "my_bookings" %>
  <%= render "my_artworks" %>
  <%= render "bookings_on_my_artworks" %>

</div>

<% if params[:tab] %>
<% content_for :after_js do %>
<%= javascript_tag do %>
var tab = '#' + '<%= params[:tab] %>';
setTimeout(function() {
$(tab).click();
}, 20);
<% end %>
<% end %>
<% end %>