config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
    controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :artworks do
    patch  "bookings/:id", to: "bookings#accept_booking", as: :confirm_booking
    put  "bookings/:id", to: "bookings#refuse_booking", as: :refuse_booking
    resources :bookings, only: [:create, :destroy]
  end

  get '/profile', to: 'profile#index'
  post '/subscribe', to: 'pages#subscribe'

  resources :bookings, only: [] do
    resources :reviews, only: :create
  end

  get 'mine', to: 'artworks#mine', as: :mine
  get '/contact' => 'pages#contact'
  get '/about' => 'pages#about'
  get '/dashboard', to: 'dashboard#index'

  scope module: 'users' do
    resources :users, only: [:show]
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable

  devise :database_authenticatable, :registerable,
         :recoverable, :trackable, :validatable,
         :omniauthable, omniauth_providers: [:facebook]

  has_many :artworks, dependent: :destroy
  has_many :bookings, dependent: :destroy
  has_many :reviews, dependent: :destroy

  def self.find_for_facebook_oauth(auth)
    user_params = auth.to_h.slice("provider", "uid")
    user_params.merge! auth.info.slice(:email, :first_name, :last_name)
    user_params[:facebook_picture_url] = auth.info.image
    user_params[:token] = auth.credentials.token
    user_params[:token_expiry] = Time.at(auth.credentials.expires_at)

    user = User.where(provider: auth.provider, uid: auth.uid).first
    user ||= User.where(email: auth.info.email).first # User did a regular sign up in the past.
    if user
      user.update(user_params)
    else
      user = User.new(user_params)
      user.password = Devise.friendly_token[0,20]  # Fake password for validation
      user.save
    end

    return user
  end

end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    user = User.find_for_facebook_oauth(request.env['omniauth.auth'])

    if user.persisted?
      sign_in_and_redirect user, event: :authentication
      set_flash_message(:notice, :success, kind: 'Facebook') if is_navigational_format?
    else
      session['devise.facebook_data'] = request.env['omniauth.auth']
      redirect_to new_user_registration_url
    end
  end
end

app/controllers/users/users_controller.rb
class Users::UsersController < ApplicationController
  def show
    if User.find(params[:id]) == current_user
      redirect_to profile_path
    else
      @user = User.find(params[:id])
      @artworks = Artwork.where(user: @user)
      @bookings = Booking.where(user: @user)
      @reviews = Review.where(booking_id: @bookings.map(&:id))
    end
  end
end

app/views/users/users/show.html.erb
<<<<<<< HEAD
<div class="screen-footer">
  <div class="container user-show">
=======
<div class="screen-footer padded">
  <div class="container flexx">
    <% avatar_url = @user.facebook_picture_url || default_avatar = "https://galerie.alittlemarket.com/galerie/sell/2626440/peintures-tableau-acrylique-abstrait-moderne-19314354-20161029-14541891a7-f00a9_big.jpg" %>
    <%= image_tag avatar_url, class: "avatar-xlarge"%>
    <div class="margined">
      <h1 class="dashboard-title">Gauthier<span class="minted"> Levha</span></h1>
      <p><i class="fa fa-envelope-o" aria-hidden="true"></i> <%= mail_to @user.email %></p>
    </div>
  </div>

  <div class="container padded">
    <h1 class="dashboard-title text-center">His<span class="minted"> art</span>works</h1>
>>>>>>> master
    <div class="row">
      <div class="col-sm-4">
        <div class="user-photo">
          <img alt="François" class="img-user" height="225" src="http://lorempixel.com/400/200" title="François" width="225" />
        </div>
        </div>
        <div class="col-sm-8 user-content">
          <h1>
            Hey, I’m <%= @user.nickname %>
          </h1>
          <div class="h5 space-top-2">
            <span class="text-normal">
              Joined in <%= @user.created_at.strftime("%B %Y") %>
            </span>
            <br> <br>
            <% if @artworks.empty? %>
              <p>This user hasn't listed any artworks yet.</p>
            <% else %>
              <h3>His artworks ( <%= @artworks.count %> )</h3>
              <div class="row">
                <% @artworks.each do |artwork| %>
                  <div class="col-xs-12 col-md-4 col-sm-6 ">
                    <div class="card">
                      <div id="card-category">
                        <p> <%= artwork.category %> </p>
                      </div>
                      <div class="card-description">
                        <h3><%= artwork.name %></h3>
                        <h5> <%= artwork.artist_name %> </h5>
                      </div>
                      <div class="card-price">
                        <p> <%= artwork.price %> € / day</p>
                      </div>
                      <div class="card-photo">
                        <%= cl_image_tag artwork.photo, height: 110, width: 150, crop: :fill %>
                      </div>
                      <div class="card-link">
                        <%= link_to '', artwork, {class: "btn-card-link"} %>
                      </div>
                    </div>
                  </div>
                <% end %>
          <% end %>
        </div>
        <div class="review-section">
          <% if @reviews %>
            <h3>Reviews ( <%= @reviews.count %> ) </h3>
            <div class="reviews">
              <div class="row">
                <% @reviews.each do |review| %>
                  <div class="col-md-2 ">
                    <div class="review-photo">
                      <img alt="François" class="img-user" height="225" src="http://lorempixel.com/200/200" title=" François" width="225" />
                    </div>
                  </div>
                <div class="col-md-10">
                    <p> <%= review.body %> </p>
                    <p> <%= review.rating %> / 5 - Posted on: <%= review.created_at.strftime("%B %Y") %> </p>
                   <div class="row space-2 line-separation">
                       <div class="col-10 col-offset-2">
                         <hr>
                       </div>
                    </div>
                </div>
              <% end %>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>
  <div class="review-form">
    <% if @bookings != nil %>
    <% @bookings.each do |booking| %>

<<<<<<< HEAD
      <h3>Leave a review:</h3>
       <%= simple_form_for [booking, booking.review], url: booking_reviews_path(booking), method: :post do |f| %>
           <%= f.input :body %>
           <%= f.input :rating %>
           <%= f.submit "Submit", class: "btn btn-primary margin-bottom" %>
             <% end %>
        <% end %>
    <% end %>
  </div>
=======
  <div class="container">
    <h1 class="dashboard-title text-center">Rate his<span class="minted"> art</span>:</h1>
    <h3 class="text-center">Available soon!</h3>
  </div>

  
>>>>>>> master
</div>