config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
    controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :artworks do
    patch  "bookings/:id", to: "bookings#accept_booking", as: :confirm_booking
    put  "bookings/:id", to: "bookings#refuse_booking", as: :refuse_booking
    resources :bookings, only: [:create, :destroy]
  end

  get '/profile', to: 'profile#index'
  post '/subscribe', to: 'pages#subscribe'

  resources :bookings, only: [] do
    resources :reviews, only: :create
  end

  get 'mine', to: 'artworks#mine', as: :mine
  get '/contact' => 'pages#contact'
  get '/about' => 'pages#about'
  get '/dashboard', to: 'dashboard#index'

  scope module: 'users' do
    resources :users, only: [:show]
  end

end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div id="footer">
<%= image_tag "/you_n_art_white.png", id: "logo-navbar" %>
  <div id="footer-content">
    <div class="container">
      <div class="row">
        <div class="col-xs-offset-3 col-xs-6 text-center">
          <ul class="list-inline">
           <li>
             <a href="#"><i class="icon-ok fa fa-facebook"></i></a>
           </li>
           <li>
             <a href="#"><i class="icon-ok fa fa-instagram"></i></a>
           </li>
           <li>
             <a href="#"><i class="icon-ok fa fa-twitter"></i></a>
           </li>
         </ul>
       </div>
     </div>
     <div class="row">
       <div class="col-xs-offset-4 col-xs-4 text-center">
         <p>Made with 💜 in Paris</p>
       </div>
     </div>
   </div>
 </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to root_path do %>
  <%= image_tag "/you_n_art_white.png", id: "logo" %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right">

    <!-- Different navigation if login or not -->
    <% if user_signed_in? %>

        <%= link_to "Find an artwork", artworks_path, class: "btn btn-navbar" %>

        <%= link_to (current_user.artworks.empty? ? "Become a collectioner" : "Add a piece of art"), new_artwork_path, class: "btn btn-navbar" %>
    <!-- Profile picture and dropdown -->
    <div class="navbar-wagon-item">
      <div class="dropdown badge-container">


        <% avatar_url = current_user.facebook_picture_url || "https://galerie.alittlemarket.com/galerie/sell/2626440/peintures-tableau-acrylique-abstrait-moderne-19314354-20161029-14541891a7-f00a9_big.jpg" %>
        <% if Booking.where(status: "Pending").count > 0 && Booking.check_user(current_user) %>
        
          <%= image_tag avatar_url, class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <div class="badge badge-red"><i class="fa fa-bell" aria-hidden="true"></i>
          </div>

        <% else %>

        <%= image_tag avatar_url, class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
        <% end %>


        <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
          <li>
            <%= link_to dashboard_path do %>
            <i class="fa fa-home"></i>  <%= t(".profile", default: "My artboard") %>
            <% end %>
          </li>

          <li>
            <%= link_to destroy_user_session_path, method: :delete do %>
            <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
            <% end %>
          </li>
        </ul>
      </div>
    </div>

    <% else %>

    <!-- Login text link -->
    <%= link_to t(".sign_up", default: "Join our collectionners"), new_user_registration_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>

    <% end %>

    <!-- Button (call-to-action) -->

  </div>

</div>