config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
    controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :artworks do
    patch  "bookings/:id", to: "bookings#accept_booking", as: :confirm_booking
    put  "bookings/:id", to: "bookings#refuse_booking", as: :refuse_booking
    resources :bookings, only: [:create, :destroy]
  end

  get '/profile', to: 'profile#index'
  post '/subscribe', to: 'pages#subscribe'

  resources :bookings, only: [] do
    resources :reviews, only: :create
  end

  get 'mine', to: 'artworks#mine', as: :mine
  get '/contact' => 'pages#contact'
  get '/about' => 'pages#about'
  get '/dashboard', to: 'dashboard#index'

  scope module: 'users' do
    resources :users, only: [:show]
  end

end

app/views/pages/about.html.erb
<div class="banner" style="background: linear-gradient(-225deg, rgba(0,101,168,0.6) 0%, rgba(0,36,61,0.6) 50%), url('<%= image_path("about.jpg")%>');">
      <div class="banner-content">
        <h2>About us</h2>
        <p>Artbnb is the only place where you can rent artworks for your own events</p>
       <%= link_to 'Take a look', artworks_path, {class: "btn change-btn-color"} %>
      </div>
    </div>

<div class="container text-center ">
  <h2> Meet the team </h2>
    <div class="text-center padded features">

      <h3>Alex</h3>
      <%= image_tag "", class: "img-circle" %>

      <h3>Gauthier</h3>
      <%= image_tag "", class: "img-circle" %>

      <h3>Francois</h3>
      <%= image_tag "", class: "img-circle" %>

      <h3>Eytan</h3>
      <%= image_tag "", class: "img-circle" %>
    </div>
</div>

<div class="text-center padded">
      <%= link_to 'Contact us', contact_path, {class: "btn btn-primary"} %>
</div>

#Need a footer and front-end
#Need to add photos

app/views/pages/contact.html.erb
<div class="container text-center" id = "center">
<form>
  <div class="form-group">
    <label for="exampleInputEmail1">Email address</label>
    <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Enter email">
    <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>
  </div>
  <div class="form-group">
    <label for="exampleTextarea">Leave your message here</label>
    <textarea class="form-control" id="exampleTextarea" rows="3"></textarea>
  </div>
  <div class="text center ">
  <button type="submit" class="btn btn-primary">Submit</button>
  </div>
</form>
</div>

app/views/pages/home.html.erb
<!-- Banner code -->
<div class="banner" style="background-image: linear-gradient(135deg, rgba(50,50,50,0.3) 5%, rgba(50,50,50,0.7) 57%), url('<%= image_path("background.jpg")%>');">
	<div class="banner-content">
		<h1 class="banner-title">You n' Art. </h1>
		<h3>Rent a <span class="minted">unique masterpiece</span> for your next <span class="minted">events.</span> </h3> <br>
     <div class="search-container">
     <%= form_tag(artworks_path, :method => "get", id: "search-form", class: "form-inline") do %>
      <%= select_tag :search, options_for_select(Artwork::ARTWORK_CATEGORY, params[:search]), prompt: "All categories", class: "navbar-wagon-search-input my-select-control" %>
      <%= text_field_tag :search_price, params[:search_price], placeholder: "Max daily budget (€)", class: "navbar-wagon-search-input my-text-control"%>
      <%= submit_tag "Take a look", :name => nil, class: "navbar-wagon-search-input form-control btn btn-home" %>
    <% end %>
    </div>
	</div>
</div>



<!-- Features code -->
<div class="container text-center padded features">
<h2 class="text-center">How it works</h2>
	<div class="row">
		<div class="col-xs-12 col-sm-6 col-md-4">
			<%= image_tag (asset_path 'check.png'), class: "features-img " %>
			<h3>Simple</h3>
			<p>Find an artwork you like. Book it. Have it delivered and set up wherever you want, to wow your guests or customers.</p>
		</div>
		<div class="col-xs-12 col-sm-6 col-md-4">
			<%= image_tag (asset_path 'statue.png'), class: "features-img" %>
			<h3>Beautiful</h3>
			<p>Our first rate art collectors have listed their most prized artworks.</p>
		</div>
		<div class="col-xs-12 col-sm-6 col-md-4">
			<%= image_tag (asset_path 'care.jpg'), class: "features-img" %>
			<h3>Safe</h3>
			<p>We get it: exposing a masterpiece at your venue can be intimidating. That’s why our services include best in class insurance policies, and on-demand security.</p>
		</div>
	</div>
</div>

<!-- Cards code -->
<div class="wrapper-grey padded">
	<div class="container">
		<h2 class="text-center">Best artworks of the moment</h2>
		<div class="row">
			<% Artwork.first(6).each do |artwork| %>
			<div class="col-xs-12 col-md-4 col-sm-6 ">
			<div class="card-white">
					<div id="card-category">
						<p> <%= artwork.category %> </p>
					</div>
					<div class="card-description">
						<h3><%= artwork.name %></h3>
						<h5> <%= artwork.artist_name %> </h5>
					</div>
					<div class="card-price">
						<p> <%= artwork.price %> € / day</p>
					</div>
					<div class="card-photo">
						<%= cl_image_tag artwork.photo, height: 110, crop: :fill %>
					</div>
					<div class="card-link">
						<%= link_to '', artwork, {class: "btn-card-link"} %>
					</div>
				</div>
			</div>
			<% end %>
		</div>
	</div>
</div>


<!-- Newsletter code -->
<div class="text-center padded newsletter">
	<h2>Get news about our artworks</h2>
	<p>Leave us your mail and get awesome piece of arts</p>

<%= form_tag(subscribe_path) do %>
  <div class="form-group form-inline">
    <%= email_field_tag :email, '', placeholder: 'Email', class: 'form-control' %>
  </div>
  <div class="form-group form-inline">
    <%= submit_tag "Subscribe", class: 'btn btn-rounded' %>
  </div>
<% end %>

</div>